{% set version = "0.9" %}

package:
  name: wcsaxes
  version: {{version}}

source:
  fn: wcsaxes-{{version}}.tar.gz
  url: https://pypi.io/packages/source/w/wcsaxes/wcsaxes-{{ version }}.tar.gz 
  md5: 5df63a4ab8fe3445fc101a9c62edea79

build:
  number: 1000
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >1.7.1
    - astropy >=1.0
    - matplotlib

test:
  # Python imports
  imports:
    - wcsaxes
  commands:
    - python -c "import wcsaxes; wcsaxes.test()"

about:
  home: http://wcsaxes.readthedocs.io
  license:  BSD 3-Clause
  summary: "WCSAxes is a framework for making plots of Astronomical data in Matplotlib."

extra:
  recipe-maintainers:
    - cadair
    - astrofrog-conda-forge
    - mwcraig
