travis:
  secure:
    BINSTAR_TOKEN: WCX8HhBvPhcsUnSnLRja53a8fmaMu5K/NnH/RQH5y5pPNHdH00KZs8dB3B/+QtorOMr5khvhqc0s07EJb58zmyccIy7lsdXGK0oYG8mhQE1lid0YE/Qs+d3qIfdMy97+pYklZB+kv8gLBVf4jmugPkwrYfZpHmfNL4GFUA7wFCkTLdQCZWalAvK2cw+0382f4I0cGcsIuSA4ictzeQB8KErIoHqlnFm39OpixcYrQAG8DeQYvmMW6J+zPMGu5XSzHCe+29eURryXXi1Mg8MLgqMJMXCBrhSxfqmgQ3ZcQkI8T8CYIIg/r/OVXf4RdgG/VloABXoCpV3bDzUOpzybLp5FdfUckCXaggB9qafso0MAmH/SZOaQNPnsCF8A5PWcA9N5k/XWDQP/nNKlFOSMSEGCBNJr6UqRU3B4Q35rK8nAMsyPkrzka7HjJfOIxV063373x4YdaX62eoib/Miou9yBsNYPNT9zWk+jtpmljJ4hm+5eCd8OXeV/IHSJnW+3XtL+Te4V59AOiNDeuvbsGTWryIm+KBk/p+UBH0X36zcsWIY1DyFWIk60UlvyDI9UBqUmZ+IHLYqj6BerTOS0hDnkn3VyEzrSzu4xpohwgXC2HmsbEuXUmyc2yo9XuepufEsKzF2swZ+z64kwlr0EG6tjgNnHqy7RPl5TukB496Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
